- name: Remove bahmni-endtb-batch before installing
  yum:  name=bahmni-endtb-batch state=absent

- name: Install bahmni-endtb-batch
  yum:  name=https://dl.bintray.com/bahmni/rpm/rpms/bahmni-endtb-batch-1.1.0-63.noarch.rpm state=present

- name: Get bahmniapps from remote location if configured
  get_url: url={{ bahmniapps_url }}
   force=yes
   dest=/opt/bahmni-web/etc/openmrs-module-bahmniapps-endtb-release-0.84.zip
   mode=0755
  when: bahmniapps_url is defined

- name: Unzip downloaded bahmniapps file
  unarchive:
   src=/opt/bahmni-web/etc/openmrs-module-bahmniapps-endtb-release-0.84.zip
   dest=/opt/bahmni-web/etc/
  when: bahmniapps_url is defined

- name: copy unzipped downloaded bahmniapps folder
  command: cp -r --no-target-directory /opt/bahmni-web/etc/openmrs-module-bahmniapps-endtb-release-0.84 /opt/bahmni-web/etc/bahmniapps
  when: bahmniapps_url is defined
