- name: Remove bahmni-endtb-batch before installing
  yum:  name=bahmni-endtb-batch state=absent

- name: Install bahmni-endtb-batch
  yum:  name=https://dl.bintray.com/bahmni/rpm/rpms/bahmni-endtb-batch-2.0.0-20.noarch.rpm state=present
