bahmni_repo_url: https://dl.bintray.com/bahmni/rpm/
implementation_name: endtb
timezone: Asia/Kolkata
omods: ["https://s3.amazonaws.com/endtb-artifacts/1.4/bahmniendtb-1.4-SNAPSHOT.omod", "https://s3.amazonaws.com/endtb-artifacts/1.3/bahmni-dataintegrity-omod-1.0-SNAPSHOT.omod", "https://s3.amazonaws.com/endtb-artifacts/1.4/bacteriology-1.0-SNAPSHOT.omod"]
