bahmni_repo_url: http://repo.mybahmni.org.s3.amazonaws.com/rpm/bahmni/
implementation_name: endtb
timezone: Asia/Kolkata
omods: ["https://s3.amazonaws.com/endtb-artifacts/2.0.0/bahmniendtb-2.0.0.omod", "https://modules.openmrs.org/modulus/api/releases/1519/download/dataintegrity-omod-4.1.0.omod", "https://s3.amazonaws.com/endtb-artifacts/1.6/bahmnicore-omod-0.88-SNAPSHOT.omod"]
